dataset:
    path : "/home/riccardo/Datasets/RAVDESS_LD_COMPLETE/"
    path_audio : "/home/riccardo/Datasets/RAVDESS_AUDIO_COMPLETE/"
    min_frames: 90
    classes : 8
    zero_start: False
    split_percentage: 0.9

model_params:
    temperature: 0.07
    feat_out: 8
    edge_weight: False
    backbone: "STCGN"
    adj_matr : "/home/riccardo/FER_SPRING/adj.npy"

training:
    lr_encoder : 0.001
    lr_linear : 0.001
    batch_size : 64          
    wd : 0.001
    momentum : 0.9
    epochs : 400
    classes : 8
    num_workers : 4
    log_model: 20
    contrastive: False
    random_aug: False
    augmented: False
    drop_kp: False
    focal: False 
