dataset:
    train:
        path : "/home/riccardo/Datasets/CAER_LD/train"
        dim_image: 32
        min_frames: 80
        classes : 7
        zero_start: True

    test: 
        path : "/home/riccardo/Datasets/CAER_LD/test"
        dim_image: 32
        min_frames: 80
        classes : 7
        zero_start: True
    
model_params:
    temperature: 0.07
    backbone: "STGN"
    adj_matr : "/home/riccardo/FER_SPRING/adj.npy"

training:
    lr_encoder : 0.01
    lr_linear : 0.001
    batch_size : 32          
    wd : 0.001
    momentum : 0.9
    epochs : 500
    classes : 7
    num_workers : 4
    log_model: 20
    contrastive: False 
