dataset:
    train:
        path : "/home/riccardo/Datasets/RAVDESS_LD10/Training_set"
        dim_image: 32
        min_frames: 90
        classes : 8
        zero_start: False
    test: 
        path : "/home/riccardo/Datasets/RAVDESS_LD10/Test_set"
        dim_image: 32
        min_frames: 90
        classes : 8
        zero_start: False 
    
model_params:
    temperature: 0.07
    feat_out: 8
    edge_weight: False
    backbone: "STCGN"
    adj_matr : "/home/riccardo/FER_SPRING/adj.npy"

training:
    lr_encoder : 0.001
    lr_linear : 0.001
    batch_size : 32          
    wd : 0.001
    momentum : 0.9
    epochs : 400
    classes : 8
    num_workers : 4
    log_model: 20
    contrastive: False
    random_aug: False 
    augmented: False
    focal: False 
