dataset:
    train:
        path : "/home/riccardo/Datasets/CAER_LD/Training_set"
        dim_image: 32
        min_frames: 80
        classes : 8
    test: 
        path : "/home/riccardo/Datasets/CAER_LD/Test_set"
        dim_image: 32
        min_frames: 80
        classes : 8 
    
model_params:
    temperature: 0.07
    backbone: "STGN"
    adj_matr : "/home/riccardo/FER_SPRING/adj.npy"

training:
    lr_encoder : 0.01
    lr_linear : 0.001
    batch_size : 32          
    wd : 0.001
    momentum : 0.9
    epochs : 100
    classes : 8
    num_workers : 4
    log_model: 20
    contrastive: False 
