dataset:
    path : "/home/riccardo/Datasets/RAVDESS_LD_COMPLETE/"
    path_audio : null
    min_frames: 90
    n_mels: 128
    classes : 8
    zero_start: False
    split_percentage: 0.9

model_params:
    temperature: 0.07
    feat_out: 8
    edge_weight: False
    backbone: "STCGN"
    adj_matr : "/home/riccardo/FER_SPRING/adj.npy"

training:
    lr_encoder : 0.001
    lr_linear : 0.001
    batch_size : 32    
    scheduler_step :  100
    scheduler_gamma : 0.9    
    wd : 0.001
    momentum : 0.9
    epochs : 2000
    classes : 8
    num_workers : 8
    log_model: 20
    contrastive: False
    unsupervised: False
    random_aug: False
    augmented: False
    drop_kp: False
    focal: False 
    audio_only : False
    audio_separate : False
